// bussiness
export const GET_COUNTRIES = 'GET_COUNTRIES';


//auth
export const LOGGED_IN = 'LOGGED_IN';
export const LOGGED_OUT = 'LOGGED_OUT';
export const SET_PROFILE = 'SET_PROFILE';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_FRIENDS_REQUEST = 'SET_FRIENDS_REQUEST';
export const SET_USER_LIST = 'SET_USER_LIST';
export const REMOVE_FRIEND_REQUEST = 'REMOVE_FRIEND_REQUEST';
export const REMOVE_FRIEND = 'REMOVE_FRIEND';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const REMOVE_PROFILE_PIC = 'REMOVE_PROFILE_PIC';
export const USER_DETAIL = 'USER_DETAIL';
export const UPDATE_CHECKIN = 'UPDATE_CHECKIN';
export const SET_FRIEND_PROFILE = 'SET_FRIEND_PROFILE'
export const CLEAR_FRIEND_DATA = 'CLEAR_FRIEND_DATA';
export const UPDATE_FRIENDS_PROFILE = 'UPDATE_FRIENDS_PROFILE';
export const SET_USER_LOCATION = 'SET_USER_LOCATION'
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const USER_DETAIL_CLEAR = 'USER_DETAIL_CLEAR';


//planner
export const CHANGE_FORM = 'CHANGE_FORM';
export const CHANGE_CITY = 'CHANGE_CITY';
export const SET_SPOTS = 'SET_SPOTS';
export const SET_SELECTED_SPOTS = 'SET_SELECTED_SPOTS';
export const SET_SPOT_DETAIL = 'SET_SPOT_DETAIL';
export const TOGGLE_FORM_LOAD = 'TOGGLE_FORM_LOAD';
export const SET_CENTER_SPOTS = 'SET_CENTER_SPOTS';
export const SAVE_FILTER_VAL = 'SAVE_FILTER_VAL';
export const RESET_FILTERS = 'RESET_FILTERS';
export const EDIT_PLANNER_DETAILS = 'EDIT_PLANNER_DETAILS';
export const UPDATE_PLANNER_DETAILS = 'UPDATE_PLANNER_DETAILS';
export const SET_CHOOSE_SPOTS = 'SET_CHOOSE_SPOTS';
export const SAVE_CENTER_SPOTS = 'SAVE_CENTER_SPOTS';

//map
export const SET_MAP_DETAIL = 'SET_MAP_DETAIL';
export const FETCHING_MAP_DETAIL = 'FETCHING_MAP_DETAIL';
export const SET_ALL_MAPS = 'SET_ALL_MAPS';
export const FETCHING_ALL_MAP = 'FETCHING_ALL_MAP';
export const SET_CURRENT_MAP_ID = 'SET_CURRENT_MAP_ID';
export const ON_SEARCH_SPOT = 'ON_SEARCH_SPOT';
export const ON_FILTER_SPOT = 'ON_FILTER_SPOT';
export const SET_WEATHER_INFO = 'SET_WEATHER_INFO';
export const SET_NEAREST_SPOT = 'SET_NEAREST_SPOT';
export const FETHCING_NEAREST_SPOT = 'FETHCING_NEAREST_SPOT';
export const SET_PAGE_COUNT = 'SET_PAGE_COUNT'
export const TOGGLE_FAV_SPOT = 'TOGGLE_FAV_SPOT';
export const SET_CENTER_CORDS = 'SET_CENTER_CORDS';
export const MAP_MARKER_ID = 'MAP_MARKER_ID';
export const REMOVE_FAV_MAP = 'REMOVE_FAV_MAP';
export const DELETE_USER_MAP = 'DELETE_USER_MAP';
export const SET_GOOGLE_SPOTS = 'SET_GOOGLE_SPOTS';
export const SAVE_SUGGESTED_SPOT = 'SAVE_SUGGESTED_SPOT';
export const SET_SPOT_MESSAGE = 'SET_SPOT_MESSAGE';
export const SET_TOGGLE_BTN = 'SET_TOGGLE_BTN';
export const SET_SEARCH_OPTION = 'SET_SEARCH_OPTION';
export const CLOSE_OVERLAY = 'CLOSE_OVERLAY';
export const SET_MAP_LIST = 'SET_MAP_LIST';
export const UPDATE_SUGGESTIONS = 'UPDATE_SUGGESTIONS';
export const SAVE_LISTED_MAP = 'SAVE_LISTED_MAP';
export const UPDATE_USER_CREATED_MAP = 'UPDATE_USER_CREATED_MAP';
export const TOGGLE_FAV_MAP = 'TOGGLE_FAV_MAP';
export const TOGGLE_FAV_BTN = 'TOGGLE_FAV_BTN';
export const SLIDER_OPEN = 'SLIDER_OPEN';
export const SLIDER_CLOSE = 'SLIDER_CLOSE'; 
export const MAP_LOADING = 'MAP_LOADING'; 
export const SET_CLICK_COUNT = 'SET_CLICK_COUNT';
export const HIDE_BUTTONS = 'HIDE_BUTTONS';
export const TOGGLE_STATE = 'TOGGLE_STATE';

//feed
export const SET_MAP_FEED = 'SET_MAP_FEED';
export const FETHCING_MAP_FEED = 'FETHCING_MAP_FEED';
export const UPDATE_MAP_FEED = 'UPDATE_MAP_FEED';
export const UPDATE_MAP_FEED_LIST = 'UPDATE_MAP_FEED_LIST'
export const DELETE_FEED_POST = 'DELETE_FEED_POST'
export const ADD_NEW_COMMENT = 'ADD_NEW_COMMENT'
export const SHARE_NEW_POST = 'SHARE_NEW_POST'
export const FETCHING_MORE_FEED = 'FETCHING_MORE_FEED'
export const APPEND_COMMENTS = 'APPEND_COMMENTS'
export const DELETE_COMMENTS = 'DELETE_COMMENTS'
export const CURRENT_COMMENT = 'CURRENT_COMMENT'
export const ADD_NEW_REPLY = 'ADD_NEW_REPLY'
export const UPDATE_REPLY_STATUS = 'UPDATE_REPLY_STATUS'
export const SET_SCROLL = 'SET_SCROLL'
export const SET_POST_FEED_EVENT = 'SET_POST_FEED_EVENT'
export const SET_FALSE = 'SET_FALSE'
export const SET_FILTERED_LIST = 'SET_FILTERED_LIST'

//messages
export const GETTING_THREAD_LIST = 'GETTING_THREAD_LIST';
export const SET_THREAD_LIST = 'SET_THREAD_LIST';
export const SEARCH_VALUE = 'SEARCH_VALUE';
export const GETTING_THREAD_MESSAGES = 'GETTING_THREAD_MESSAGES';
export const SET_THREAD_MESSAGES = 'SET_THREAD_MESSAGES';
export const CURRENT_THREAD_DETAIL = 'CURRENT_THREAD_DETAIL';
export const SET_FRIEND_SEARCH = 'SET_FRIEND_SEARCH';
export const SET_SELECTED_USERS = 'SET_SELECTED_USERS';
export const UPDATE_THREAD_MEMBERS = 'UPDATE_THREAD_MEMBERS';
export const REMOVE_MEMBER = 'REMOVE_MEMBER';
export const UPDATE_ROLE = 'UPDATE_ROLE';
export const SET_SEARCHING_CHAT = 'SET_SEARCHING_CHAT';
export const CHANGE_CONVERSATION_FORM = 'CHANGE_CONVERSATION_FORM';
export const UPDATE_SELECTED_USERS = 'UPDATE_SELECTED_USERS';
export const CLEAR_FORM = 'CLEAR_FORM';
export const UPDATE_ROOM_LIST = 'UPDATE_ROOM_LIST';
export const CREATING_GROUP = 'CREATING_GROUP';
export const UPDATING_THREAD = 'UPDATING_THREAD';
export const SET_GROUP_DETAIL = 'SET_GROUP_DETAIL';
export const LOADING_PROFILE_PIC = 'LOADING_PROFILE_PIC';
export const ON_CHANGE_NAME = 'ON_CHANGE_NAME';
export const REMOVE_PICTURE = 'REMOVE_PICTURE';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const UPDATE_THREAD_LIST = 'UPDATE_THREAD_LIST';
export const CLEAR_CURRENT_THREAD = 'CLEAR_CURRENT_THREAD';
export const SET_SCHEDULE_MESSAGES = 'SET_SCHEDULE_MESSAGES';
export const ADD_SCHEDULE_MESSAGE = 'ADD_SCHEDULE_MESSAGE';
export const DELETE_SCHEDULE_MESSAGE = 'DELETE_SCHEDULE_MESSAGE';
export const EDIT_SCHEDULE_MESSAGE = 'EDIT_SCHEDULE_MESSAGE';
export const SAVE_POST_MESSAGE = 'SAVE_POST_MESSAGE';

// notificattions
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const SET_LOADING_N = 'SET_LOADING_N';
export const SET_COUNT = 'SET_COUNT';
export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION';

//socket
export const SET_SOCKET = 'SET_SOCKET';
export const SET_CHECKIN_USERS = 'SET_CHECKIN_USERS';
export const UPDATE_CHECKIN_USER = 'UPDATE_CHECKIN_USER';
export const UPDATE_CHECKIN_USER_MESSAGE = 'UPDATE_CHECKIN_USER_MESSAGE';
export const UPDATE_SPOT_USER_MESSAGE = 'UPDATE_SPOT_USER_MESSAGE';
export const REMOVE_POPUP = 'REMOVE_POPUP';

//categories
export const SET_CATEGORIES = 'SET_CATEGORIES';

//activity
export const SET_ACTIVITY = 'SET_ACTIVITY';
export const SET_LOADING = 'SET_LOADING';

//search
export const SET_SEARCH_DETAIL = 'SET_SEARCH_DETAIL';

//ui
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_ACTIVE_TAB_INDEX = 'SET_ACTIVE_TAB_INDEX';
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';
export const MODAL_VISIBLE = 'MODAL_VISIBLE';
